/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/* INTEGRANTES:
Gilberto de Melo Junior RA: 125111350102 
Henrique Barbosa RA: 125111368512 
Luiz Gustavo RA: 
Marcus Gustavo Oliveira Sigrist Romão RA: 125111372918 */

package a3programacaosolucoescomp;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.Date;
import java.util.ArrayList;

/**
 *
 * @author Henrique
 */
public class A3ProgramacaoSolucoesComp extends javax.swing.JFrame {

    /**
     * Creates new form menuUI
     */
    public A3ProgramacaoSolucoesComp() {
        initComponents();
    }
    
    public Usuario usuario;
    CardLayout card;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialog = new javax.swing.JDialog();
        controladorDialogPanel = new javax.swing.JPanel();
        deletarContaPanel = new javax.swing.JPanel();
        deletarLabel = new javax.swing.JLabel();
        confirmaDeletarButton = new javax.swing.JButton();
        negaDeletarButton = new javax.swing.JButton();
        alterarDadosPanel = new javax.swing.JPanel();
        novosDadosLabel = new javax.swing.JLabel();
        atualizaDadosButton = new javax.swing.JButton();
        alteraEmailLabel = new javax.swing.JLabel();
        alteraEmailTextField = new javax.swing.JTextField();
        alteraSenhaLabel = new javax.swing.JLabel();
        alteraSenhaTextField = new javax.swing.JTextField();
        loginPanel = new javax.swing.JPanel();
        loginEmailLabel = new javax.swing.JLabel();
        loginSenhaLabel = new javax.swing.JLabel();
        loginEmailTextField = new javax.swing.JTextField();
        loginSenhaTextField = new javax.swing.JTextField();
        loginConfirmaButton = new javax.swing.JButton();
        dadosIncorretosLabel = new javax.swing.JLabel();
        controladorJFramePanel = new javax.swing.JPanel();
        inicioPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        cadastrarButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        logadoPanel = new javax.swing.JPanel();
        usuarioLogadoLabel = new javax.swing.JLabel();
        eventoLabel = new javax.swing.JLabel();
        contatoLogadoLabel = new javax.swing.JLabel();
        sairButton = new javax.swing.JButton();
        mudarCadastroButton = new javax.swing.JButton();
        deletarContaLabel = new javax.swing.JButton();
        cadastrarPanel = new javax.swing.JPanel();
        nomeTextField = new javax.swing.JTextField();
        nomeLabel = new javax.swing.JLabel();
        sobrenomeLabel = new javax.swing.JLabel();
        sobrenomeTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        senhaLabel = new javax.swing.JLabel();
        senhaTextField = new javax.swing.JTextField();
        cpfLabel = new javax.swing.JLabel();
        cpfTextField = new javax.swing.JTextField();
        rgLabel = new javax.swing.JLabel();
        rgTextField = new javax.swing.JTextField();
        enderecoLabel = new javax.swing.JLabel();
        enderecoTextField = new javax.swing.JTextField();
        cepLabel = new javax.swing.JLabel();
        cepTextField = new javax.swing.JTextField();
        telefoneLabel = new javax.swing.JLabel();
        telefoneTextField = new javax.swing.JTextField();
        contatoLabel = new javax.swing.JLabel();
        contatoTextField = new javax.swing.JTextField();
        tipoUsuarioCheckBox = new javax.swing.JCheckBox();
        empresaLabel = new javax.swing.JLabel();
        cnpjLabel = new javax.swing.JLabel();
        empresaTextField = new javax.swing.JTextField();
        cnpjTextField = new javax.swing.JTextField();
        voltarInicioButton = new javax.swing.JButton();
        confirmarCadastroButton = new javax.swing.JButton();

        Dialog.setPreferredSize(new java.awt.Dimension(1000, 300));
        Dialog.setSize(new java.awt.Dimension(300, 150));

        controladorDialogPanel.setPreferredSize(new java.awt.Dimension(300, 150));
        controladorDialogPanel.setLayout(new java.awt.CardLayout());

        deletarContaPanel.setBackground(new java.awt.Color(255, 255, 255));

        deletarLabel.setBackground(new java.awt.Color(255, 255, 255));
        deletarLabel.setForeground(new java.awt.Color(0, 0, 0));
        deletarLabel.setText("Tem certeza que deseja deletar sua conta?");

        confirmaDeletarButton.setBackground(new java.awt.Color(204, 204, 204));
        confirmaDeletarButton.setForeground(new java.awt.Color(0, 0, 0));
        confirmaDeletarButton.setText("Sim");
        confirmaDeletarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmaDeletarButtonMouseClicked(evt);
            }
        });

        negaDeletarButton.setBackground(new java.awt.Color(204, 204, 204));
        negaDeletarButton.setForeground(new java.awt.Color(0, 0, 0));
        negaDeletarButton.setText("Não");
        negaDeletarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                negaDeletarButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout deletarContaPanelLayout = new javax.swing.GroupLayout(deletarContaPanel);
        deletarContaPanel.setLayout(deletarContaPanelLayout);
        deletarContaPanelLayout.setHorizontalGroup(
            deletarContaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletarContaPanelLayout.createSequentialGroup()
                .addGroup(deletarContaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deletarContaPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(confirmaDeletarButton)
                        .addGap(42, 42, 42)
                        .addComponent(negaDeletarButton))
                    .addGroup(deletarContaPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(deletarLabel)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        deletarContaPanelLayout.setVerticalGroup(
            deletarContaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletarContaPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(deletarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deletarContaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmaDeletarButton)
                    .addComponent(negaDeletarButton))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        controladorDialogPanel.add(deletarContaPanel, "deletarContaPanel");

        alterarDadosPanel.setBackground(new java.awt.Color(255, 255, 255));

        novosDadosLabel.setBackground(new java.awt.Color(255, 255, 255));
        novosDadosLabel.setForeground(new java.awt.Color(0, 0, 0));
        novosDadosLabel.setText("Digite seu novo e-mail e senha:");
        novosDadosLabel.setToolTipText("");

        atualizaDadosButton.setBackground(new java.awt.Color(204, 204, 204));
        atualizaDadosButton.setForeground(new java.awt.Color(0, 0, 0));
        atualizaDadosButton.setText("Atualizar");
        atualizaDadosButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizaDadosButtonMouseClicked(evt);
            }
        });

        alteraEmailLabel.setBackground(new java.awt.Color(255, 255, 255));
        alteraEmailLabel.setForeground(new java.awt.Color(0, 0, 0));
        alteraEmailLabel.setText("E-mail:");

        alteraEmailTextField.setBackground(new java.awt.Color(204, 204, 204));

        alteraSenhaLabel.setBackground(new java.awt.Color(255, 255, 255));
        alteraSenhaLabel.setForeground(new java.awt.Color(0, 0, 0));
        alteraSenhaLabel.setText("Senha:");

        alteraSenhaTextField.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout alterarDadosPanelLayout = new javax.swing.GroupLayout(alterarDadosPanel);
        alterarDadosPanel.setLayout(alterarDadosPanelLayout);
        alterarDadosPanelLayout.setHorizontalGroup(
            alterarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterarDadosPanelLayout.createSequentialGroup()
                .addGroup(alterarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alterarDadosPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(novosDadosLabel))
                    .addGroup(alterarDadosPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(alterarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(alterarDadosPanelLayout.createSequentialGroup()
                                .addComponent(alteraSenhaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alteraSenhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(alterarDadosPanelLayout.createSequentialGroup()
                                .addComponent(alteraEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alteraEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atualizaDadosButton)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        alterarDadosPanelLayout.setVerticalGroup(
            alterarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterarDadosPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(novosDadosLabel)
                .addGroup(alterarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alterarDadosPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(alterarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alteraEmailLabel)
                            .addComponent(alteraEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(alterarDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alteraSenhaLabel)
                            .addComponent(alteraSenhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(alterarDadosPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(atualizaDadosButton)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        controladorDialogPanel.add(alterarDadosPanel, "alterarDadosPanel");

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setPreferredSize(new java.awt.Dimension(300, 150));

        loginEmailLabel.setBackground(new java.awt.Color(255, 255, 255));
        loginEmailLabel.setForeground(new java.awt.Color(0, 0, 0));
        loginEmailLabel.setText("E-mail:");

        loginSenhaLabel.setBackground(new java.awt.Color(255, 255, 255));
        loginSenhaLabel.setForeground(new java.awt.Color(0, 0, 0));
        loginSenhaLabel.setText("Senha:");

        loginEmailTextField.setBackground(new java.awt.Color(204, 204, 204));

        loginSenhaTextField.setBackground(new java.awt.Color(204, 204, 204));

        loginConfirmaButton.setBackground(new java.awt.Color(204, 204, 204));
        loginConfirmaButton.setForeground(new java.awt.Color(0, 0, 0));
        loginConfirmaButton.setText("Login");
        loginConfirmaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginConfirmaButtonMouseClicked(evt);
            }
        });

        dadosIncorretosLabel.setFont(new java.awt.Font("Corbel", 0, 10)); // NOI18N
        dadosIncorretosLabel.setForeground(new java.awt.Color(255, 0, 51));
        dadosIncorretosLabel.setText("Dados incorretos!");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(loginEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loginEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(loginSenhaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loginSenhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(loginConfirmaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dadosIncorretosLabel)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginEmailLabel)
                    .addComponent(loginEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginSenhaLabel)
                    .addComponent(loginSenhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginConfirmaButton)
                    .addComponent(dadosIncorretosLabel))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        controladorDialogPanel.add(loginPanel, "loginPanel");

        javax.swing.GroupLayout DialogLayout = new javax.swing.GroupLayout(Dialog.getContentPane());
        Dialog.getContentPane().setLayout(DialogLayout);
        DialogLayout.setHorizontalGroup(
            DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controladorDialogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        DialogLayout.setVerticalGroup(
            DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controladorDialogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 102));
        setForeground(new java.awt.Color(255, 255, 102));
        setName("Quem vai?"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 400));

        controladorJFramePanel.setPreferredSize(new java.awt.Dimension(400, 400));
        controladorJFramePanel.setLayout(new java.awt.CardLayout());

        inicioPanel.setBackground(new java.awt.Color(103, 10, 96));
        inicioPanel.setPreferredSize(new java.awt.Dimension(400, 400));

        logoLabel.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel.setText("Quem vai?");

        cadastrarButton.setBackground(new java.awt.Color(9, 70, 0));
        cadastrarButton.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        cadastrarButton.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarButton.setText("Cadastrar");
        cadastrarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarButton.setName("cadastrarButton"); // NOI18N
        cadastrarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarButtonMouseClicked(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(9, 70, 0));
        loginButton.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.setName("loginButton"); // NOI18N
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout inicioPanelLayout = new javax.swing.GroupLayout(inicioPanel);
        inicioPanel.setLayout(inicioPanelLayout);
        inicioPanelLayout.setHorizontalGroup(
            inicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioPanelLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(logoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(inicioPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(cadastrarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        inicioPanelLayout.setVerticalGroup(
            inicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(logoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(inicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        controladorJFramePanel.add(inicioPanel, "inicioPanel");

        logadoPanel.setBackground(new java.awt.Color(103, 10, 96));
        logadoPanel.setPreferredSize(new java.awt.Dimension(400, 400));

        usuarioLogadoLabel.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        usuarioLogadoLabel.setForeground(new java.awt.Color(255, 255, 255));
        usuarioLogadoLabel.setText("Bem-vindo(a) Usuário!");

        eventoLabel.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        eventoLabel.setForeground(new java.awt.Color(255, 255, 255));
        eventoLabel.setText("Nenhum evento disponível no momento.");

        contatoLogadoLabel.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        contatoLogadoLabel.setForeground(new java.awt.Color(255, 255, 255));
        contatoLogadoLabel.setText("Contato disponível: Nenhum");

        sairButton.setBackground(new java.awt.Color(9, 70, 0));
        sairButton.setForeground(new java.awt.Color(255, 255, 255));
        sairButton.setText("Sair");
        sairButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairButtonMouseClicked(evt);
            }
        });

        mudarCadastroButton.setBackground(new java.awt.Color(9, 70, 0));
        mudarCadastroButton.setForeground(new java.awt.Color(255, 255, 255));
        mudarCadastroButton.setText("Alterar email/senha");
        mudarCadastroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mudarCadastroButtonMouseClicked(evt);
            }
        });

        deletarContaLabel.setBackground(new java.awt.Color(9, 70, 0));
        deletarContaLabel.setForeground(new java.awt.Color(255, 255, 255));
        deletarContaLabel.setText("Deletar conta");
        deletarContaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletarContaLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout logadoPanelLayout = new javax.swing.GroupLayout(logadoPanel);
        logadoPanel.setLayout(logadoPanelLayout);
        logadoPanelLayout.setHorizontalGroup(
            logadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logadoPanelLayout.createSequentialGroup()
                .addGroup(logadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logadoPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletarContaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mudarCadastroButton))
                    .addGroup(logadoPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(logadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eventoLabel)
                            .addComponent(usuarioLogadoLabel)
                            .addComponent(contatoLogadoLabel))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        logadoPanelLayout.setVerticalGroup(
            logadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logadoPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(usuarioLogadoLabel)
                .addGap(103, 103, 103)
                .addComponent(eventoLabel)
                .addGap(31, 31, 31)
                .addComponent(contatoLogadoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(logadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sairButton)
                    .addComponent(deletarContaLabel)
                    .addComponent(mudarCadastroButton))
                .addGap(28, 28, 28))
        );

        controladorJFramePanel.add(logadoPanel, "logadoPanel");

        cadastrarPanel.setBackground(new java.awt.Color(103, 10, 96));
        cadastrarPanel.setPreferredSize(new java.awt.Dimension(400, 400));

        nomeTextField.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        nomeTextField.setToolTipText("");

        nomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        nomeLabel.setLabelFor(nomeTextField);
        nomeLabel.setText("Nome");

        sobrenomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        sobrenomeLabel.setLabelFor(senhaTextField);
        sobrenomeLabel.setText("Sobrenome");

        sobrenomeTextField.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N

        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email");

        emailTextField.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        emailTextField.setToolTipText("");

        senhaLabel.setForeground(new java.awt.Color(255, 255, 255));
        senhaLabel.setText("Senha");
        senhaLabel.setToolTipText("");

        senhaTextField.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N

        cpfLabel.setForeground(new java.awt.Color(255, 255, 255));
        cpfLabel.setText("CPF");

        cpfTextField.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        cpfTextField.setToolTipText("");

        rgLabel.setForeground(new java.awt.Color(255, 255, 255));
        rgLabel.setText("RG");

        rgTextField.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        rgTextField.setToolTipText("");

        enderecoLabel.setForeground(new java.awt.Color(255, 255, 255));
        enderecoLabel.setText("Endereço");

        enderecoTextField.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        enderecoTextField.setToolTipText("");

        cepLabel.setForeground(new java.awt.Color(255, 255, 255));
        cepLabel.setText("CEP");

        cepTextField.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        cepTextField.setToolTipText("");

        telefoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        telefoneLabel.setText("Telefone");

        telefoneTextField.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        telefoneTextField.setToolTipText("");

        contatoLabel.setForeground(new java.awt.Color(255, 255, 255));
        contatoLabel.setText("Forma de contato");

        contatoTextField.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        contatoTextField.setToolTipText("");

        tipoUsuarioCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        tipoUsuarioCheckBox.setText("Promoter");
        tipoUsuarioCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tipoUsuarioCheckBoxStateChanged(evt);
            }
        });

        empresaLabel.setForeground(new java.awt.Color(255, 255, 255));
        empresaLabel.setText("Nome da empresa");

        cnpjLabel.setForeground(new java.awt.Color(255, 255, 255));
        cnpjLabel.setText("CNPJ");

        empresaTextField.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        empresaTextField.setToolTipText("");
        empresaTextField.setEnabled(false);

        cnpjTextField.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        cnpjTextField.setToolTipText("");
        cnpjTextField.setEnabled(false);

        voltarInicioButton.setBackground(new java.awt.Color(9, 70, 0));
        voltarInicioButton.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        voltarInicioButton.setForeground(new java.awt.Color(255, 255, 255));
        voltarInicioButton.setText("Voltar");
        voltarInicioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarInicioButtonMouseClicked(evt);
            }
        });

        confirmarCadastroButton.setBackground(new java.awt.Color(9, 70, 0));
        confirmarCadastroButton.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        confirmarCadastroButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmarCadastroButton.setText("Cadastrar");
        confirmarCadastroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmarCadastroButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cadastrarPanelLayout = new javax.swing.GroupLayout(cadastrarPanel);
        cadastrarPanel.setLayout(cadastrarPanelLayout);
        cadastrarPanelLayout.setHorizontalGroup(
            cadastrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastrarPanelLayout.createSequentialGroup()
                        .addComponent(tipoUsuarioCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(cadastrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastrarPanelLayout.createSequentialGroup()
                                .addComponent(empresaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empresaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cadastrarPanelLayout.createSequentialGroup()
                                .addComponent(cnpjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cnpjTextField)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(cadastrarPanelLayout.createSequentialGroup()
                        .addGroup(cadastrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastrarPanelLayout.createSequentialGroup()
                                .addComponent(telefoneLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(telefoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(cepLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cepTextField))
                            .addGroup(cadastrarPanelLayout.createSequentialGroup()
                                .addGroup(cadastrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cpfLabel)
                                    .addGroup(cadastrarPanelLayout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(cpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rgLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rgTextField))
                            .addGroup(cadastrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastrarPanelLayout.createSequentialGroup()
                                    .addComponent(emailLabel)
                                    .addGap(10, 10, 10)
                                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(senhaLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(senhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(cadastrarPanelLayout.createSequentialGroup()
                                    .addComponent(nomeLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(sobrenomeLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sobrenomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(cadastrarPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(voltarInicioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(confirmarCadastroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarPanelLayout.createSequentialGroup()
                                .addComponent(contatoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contatoTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarPanelLayout.createSequentialGroup()
                                .addComponent(enderecoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enderecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        cadastrarPanelLayout.setVerticalGroup(
            cadastrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sobrenomeLabel)
                    .addComponent(sobrenomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadastrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaLabel)
                    .addComponent(senhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadastrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLabel)
                    .addComponent(cpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rgLabel)
                    .addComponent(rgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadastrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cepLabel)
                    .addComponent(cepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneLabel)
                    .addComponent(telefoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadastrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoLabel)
                    .addComponent(enderecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadastrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contatoLabel)
                    .addComponent(contatoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoUsuarioCheckBox)
                    .addComponent(empresaLabel)
                    .addComponent(empresaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadastrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnpjLabel)
                    .addComponent(cnpjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(cadastrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarCadastroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltarInicioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        controladorJFramePanel.add(cadastrarPanel, "cadastrarPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controladorJFramePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controladorJFramePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(414, 437));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarButtonMouseClicked
        card = (CardLayout)controladorJFramePanel.getLayout();
        card.show(controladorJFramePanel, "cadastrarPanel");
    }//GEN-LAST:event_cadastrarButtonMouseClicked

    private void voltarInicioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarInicioButtonMouseClicked
        if(tipoUsuarioCheckBox.isSelected()){
            usuario = new Promoter(nomeTextField.getText(), sobrenomeTextField.getText(), emailTextField.getText(), senhaTextField.getText(), cpfTextField.getText(), rgTextField.getText(), telefoneTextField.getText(), cepTextField.getText(), enderecoTextField.getText(), contatoTextField.getText(), "promoter", empresaTextField.getText(), cnpjTextField.getText());   
            empresaTextField.setEnabled(false);
            empresaTextField.setText("");
            cnpjTextField.setEnabled(false);
            cnpjTextField.setText("");
        }
        card = (CardLayout)controladorJFramePanel.getLayout();
        card.show(controladorJFramePanel, "inicioPanel");
    }//GEN-LAST:event_voltarInicioButtonMouseClicked

    private void confirmarCadastroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarCadastroButtonMouseClicked
        if(tipoUsuarioCheckBox.isSelected()){
            usuario = new Promoter(nomeTextField.getText(), sobrenomeTextField.getText(), emailTextField.getText(), senhaTextField.getText(), cpfTextField.getText(), rgTextField.getText(), telefoneTextField.getText(), cepTextField.getText(), enderecoTextField.getText(), contatoTextField.getText(), "promoter", empresaTextField.getText(), cnpjTextField.getText());   
            empresaTextField.setEnabled(false);
            empresaTextField.setText("");
            cnpjTextField.setEnabled(false);
            cnpjTextField.setText("");
        }else{
            usuario = new Usuario(nomeTextField.getText(), sobrenomeTextField.getText(), emailTextField.getText(), senhaTextField.getText(), cpfTextField.getText(), rgTextField.getText(), telefoneTextField.getText(), cepTextField.getText(), enderecoTextField.getText(), contatoTextField.getText(), "participante");   
        }
        nomeTextField.setText("");
        sobrenomeTextField.setText("");
        emailTextField.setText("");
        senhaTextField.setText("");
        cpfTextField.setText("");
        rgTextField.setText("");
        telefoneTextField.setText("");
        cepTextField.setText("");
        enderecoTextField.setText("");
        contatoTextField.setText("");
        usuarioLogadoLabel.setText("Bem-vindo(a) " + usuario.getPrimeiroNome());
        contatoLogadoLabel.setText("Contato disponível: " + usuario.getContato());
        card = (CardLayout)controladorJFramePanel.getLayout();
        card.show(controladorJFramePanel, "logadoPanel");
    }//GEN-LAST:event_confirmarCadastroButtonMouseClicked

    private void tipoUsuarioCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tipoUsuarioCheckBoxStateChanged
        if(tipoUsuarioCheckBox.isSelected()){
            empresaTextField.setEnabled(true);
            cnpjTextField.setEnabled(true);
        }else{
            empresaTextField.setEnabled(false);
            empresaTextField.setText("");
            cnpjTextField.setEnabled(false);
            cnpjTextField.setText("");
        }
    }//GEN-LAST:event_tipoUsuarioCheckBoxStateChanged

    private void sairButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairButtonMouseClicked
        card = (CardLayout)controladorJFramePanel.getLayout();
        card.show(controladorJFramePanel, "inicioPanel");
    }//GEN-LAST:event_sairButtonMouseClicked

    private void confirmaDeletarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmaDeletarButtonMouseClicked
        usuario = new Usuario();
        Dialog.setVisible(false);
        card = (CardLayout)controladorJFramePanel.getLayout();
        card.show(controladorJFramePanel, "inicioPanel");
    }//GEN-LAST:event_confirmaDeletarButtonMouseClicked

    private void negaDeletarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_negaDeletarButtonMouseClicked
        Dialog.setVisible(false);
    }//GEN-LAST:event_negaDeletarButtonMouseClicked

    private void deletarContaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletarContaLabelMouseClicked
        card = (CardLayout)controladorDialogPanel.getLayout();
        card.show(controladorDialogPanel, "deletarContaPanel");
        Dialog.setVisible(true);
    }//GEN-LAST:event_deletarContaLabelMouseClicked

    private void mudarCadastroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mudarCadastroButtonMouseClicked
        alteraSenhaTextField.setText(usuario.getSenha());
        alteraEmailTextField.setText(usuario.getEmail());
        card = (CardLayout)controladorDialogPanel.getLayout();
        card.show(controladorDialogPanel, "alterarDadosPanel");
        Dialog.setVisible(true);
    }//GEN-LAST:event_mudarCadastroButtonMouseClicked

    private void atualizaDadosButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizaDadosButtonMouseClicked
        usuario.setEmail(alteraEmailTextField.getText());
        usuario.setSenha(alteraSenhaTextField.getText());
        Dialog.setVisible(false);
    }//GEN-LAST:event_atualizaDadosButtonMouseClicked

    private void loginConfirmaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginConfirmaButtonMouseClicked
        try{
            if(loginEmailTextField.getText().equals(usuario.getEmail()) && loginSenhaTextField.getText().equals(usuario.getSenha())){
                Dialog.setVisible(false);
                usuarioLogadoLabel.setText("Bem-vindo(a) " + usuario.getPrimeiroNome());
                contatoLogadoLabel.setText("Contato disponível: " + usuario.getContato());
                card = (CardLayout)controladorJFramePanel.getLayout();
                card.show(controladorJFramePanel, "logadoPanel");
            }else{
                dadosIncorretosLabel.setVisible(true);
            }
        }catch(Exception ex){
            dadosIncorretosLabel.setVisible(true);
        }
    }//GEN-LAST:event_loginConfirmaButtonMouseClicked

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        card = (CardLayout)controladorDialogPanel.getLayout();
        card.show(controladorDialogPanel, "loginPanel");
        dadosIncorretosLabel.setVisible(false);
        loginEmailTextField.setText("");
        loginSenhaTextField.setText("");
        Dialog.setVisible(true);
    }//GEN-LAST:event_loginButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A3ProgramacaoSolucoesComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A3ProgramacaoSolucoesComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A3ProgramacaoSolucoesComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A3ProgramacaoSolucoesComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A3ProgramacaoSolucoesComp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialog;
    private javax.swing.JLabel alteraEmailLabel;
    private javax.swing.JTextField alteraEmailTextField;
    private javax.swing.JLabel alteraSenhaLabel;
    private javax.swing.JTextField alteraSenhaTextField;
    private javax.swing.JPanel alterarDadosPanel;
    private javax.swing.JButton atualizaDadosButton;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JPanel cadastrarPanel;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JTextField cepTextField;
    private javax.swing.JLabel cnpjLabel;
    private javax.swing.JTextField cnpjTextField;
    private javax.swing.JButton confirmaDeletarButton;
    private javax.swing.JButton confirmarCadastroButton;
    private javax.swing.JLabel contatoLabel;
    private javax.swing.JLabel contatoLogadoLabel;
    private javax.swing.JTextField contatoTextField;
    private javax.swing.JPanel controladorDialogPanel;
    private javax.swing.JPanel controladorJFramePanel;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JTextField cpfTextField;
    private javax.swing.JLabel dadosIncorretosLabel;
    private javax.swing.JButton deletarContaLabel;
    private javax.swing.JPanel deletarContaPanel;
    private javax.swing.JLabel deletarLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel empresaLabel;
    private javax.swing.JTextField empresaTextField;
    private javax.swing.JLabel enderecoLabel;
    private javax.swing.JTextField enderecoTextField;
    private javax.swing.JLabel eventoLabel;
    private javax.swing.JPanel inicioPanel;
    private javax.swing.JPanel logadoPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton loginConfirmaButton;
    private javax.swing.JLabel loginEmailLabel;
    private javax.swing.JTextField loginEmailTextField;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel loginSenhaLabel;
    private javax.swing.JTextField loginSenhaTextField;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton mudarCadastroButton;
    private javax.swing.JButton negaDeletarButton;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JLabel novosDadosLabel;
    private javax.swing.JLabel rgLabel;
    private javax.swing.JTextField rgTextField;
    private javax.swing.JButton sairButton;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JTextField senhaTextField;
    private javax.swing.JLabel sobrenomeLabel;
    private javax.swing.JTextField sobrenomeTextField;
    private javax.swing.JLabel telefoneLabel;
    private javax.swing.JTextField telefoneTextField;
    private javax.swing.JCheckBox tipoUsuarioCheckBox;
    private javax.swing.JLabel usuarioLogadoLabel;
    private javax.swing.JButton voltarInicioButton;
    // End of variables declaration//GEN-END:variables
}
